%% for all C mutations
subplot(3,2,1)
scatter(CA{:,'Mut'}, CA{:, 'occurrence'}, 'filled')
title('C<-A Mutations')
xlabel('Mutations')
ylabel('% of occurrences')
subplot(3,2,3)
scatter(CG{:,'Mut'}, CG{:, 'occurrence'}, 'filled')
title('C<-G Mutations')
xlabel('Mutations')
ylabel('% of occurrences')
subplot(3,2,5)
scatter(CT{:,'Mut'}, CT{:, 'occurrence'}, 'filled')
title('C<-T Mutations')
xlabel('Mutations')
ylabel('% of occurrences')

%% for all T mutations
subplot(3,2,2)
scatter(TA{:,'Mut'}, TA{:, 'occurrence'}, 'filled')
title('T<-A Mutations')
xlabel('Mutations')
ylabel('% of occurrences')
subplot(3,2,4)
scatter(TC{:,'Mut'}, TC{:, 'occurrence'}, 'filled')
title('T<-C Mutations')
xlabel('Mutations')
ylabel('% of occurrences')
subplot(3,2,6)
scatter(TG{:,'Mut'}, TG{:, 'occurrence'}, 'filled')
title('T<-G Mutations')
xlabel('Mutations')
ylabel('% of occurrences')
